M48
; DRILL file {KiCad 7.0.2} date Thu Apr 20 14:17:52 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-20T14:17:52-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X114.935Y-59.055
X114.935Y-116.205
X190.5Y-62.992
X190.5Y-116.205
T0
M30
